name: build
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
concurrency:
  group: ${{ github.ref }}-plugins
  cancel-in-progress: true

jobs:


#============================================
# =================== SETUP =================
# ===========================================
  get_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix_json=$(cat .github/plugins.json | jq -c)
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT


#============================================
#==================== LINUX =================
#============================================
  build_windows:
    needs: get_plugins    
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64

      - name: Download source
        run: |
         cd ${{ matrix.directory }}
         wget https://github.com/ClassiCube/ClassiCube/archive/master.zip
         unzip -q master.zip
         wget https://cs.classicube.net/client/latest/ClassiCube.exe -O cc-32.exe
         wget https://cs.classicube.net/client/latest/ClassiCube.64.exe -O cc-64.exe

      - name: Compile plugin
        env:
          WIN32_CC: "i686-w64-mingw32-gcc"
          WIN64_CC: "x86_64-w64-mingw32-gcc"
          INCS:  "-I ./ClassiCube-master/src/"
          FLAGS: "-O1 -g -fno-stack-protector -fno-math-errno -Qn -fvisibility=hidden -nostartfiles -Wl,--entry=0 -shared -fPIC -Werror -L. -lClassiCube"
        run: |         
         cd ${{ matrix.directory }}

         rm ClassiCube.exe ClassiCube.def
         cp cc-32.exe ClassiCube.exe
         gendef ClassiCube.exe
         i686-w64-mingw32-dlltool -d ClassiCube.def -l libClassiCube.a -D ClassiCube.exe
         ${{ env.WIN32_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_32.dll

         rm ClassiCube.exe ClassiCube.def
         cp cc-64.exe ClassiCube.exe
         gendef ClassiCube.exe
         x86_64-w64-mingw32-dlltool -d ClassiCube.def -l libClassiCube.a -D ClassiCube.exe
         ${{ env.WIN64_CC }} *.c ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_64.dll
          

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_32.dll'
          DEST_NAME:   '${{ matrix.out_name }}_windows_32.dll'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'

      - uses: ./.github/actions/upload_build
        with:
          SOURCE_FILE: '${{ matrix.directory }}/${{ matrix.out_name }}_64.dll'
          DEST_NAME:   '${{ matrix.out_name }}_windows_64.dll'
          GROUP_NAME:  '${{ matrix.out_name }}'
          GH_TOKEN:    '${{ secrets.GITHUB_TOKEN }}'


      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to produce ${{ matrix.out_name }} plugin for Windows'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
