name: build
on: push
jobs:
  get_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix_json=$(cat .github/plugins.json | jq -c '@json')
          matrix_json="${matrix_json:1:-1}"
          echo "$matrix_json"
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  build_linux:
    needs: get_plugins
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
