name: build
on: push
jobs:
  get_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          echo "matrix=$(cat .github/plugins.json | jq -R '@json')" >> $GITHUB_OUTPUT

  build_linux:
    needs: get_plugins
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
