name: build
on: push
jobs:
  get_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix_json=$(cat .github/plugins.json | jq -c)
          echo "$matrix_json"
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  build_linux:
    needs: get_plugins
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.get_plugins.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.directory }}
    - run: echo ${{ matrix.out_name }}
    - name: Compile plugin
      env: 
        INCS: "-I ~/ClassiCube/src/ -I ./src/"
        FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn -nostartfiles -Wl,--entry=0"
      run: |
       wget github.com/ClassiCube/ClassiCube/archive/master.zip
       unzip master.zip
       cd ${{ matrix.directory }}
          
       gcc -m32 ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_32.so
       gcc -m64 ${{ env.INCS }} ${{ env.FLAGS }} -o ${{ matrix.out_name }}_64.so
      
